# Generated by Django 6.0.4 on 2026-04-12 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0002_warehouse_alter_item_category"),
        ("production", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="destination_warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_deposits",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="source_warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_withdrawals",
                to="warehouse.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("tx_type", models.CharField(max_length=20)),
                ("reference_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bom.item"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StockRecord",
        ),
        migrations.DeleteModel(
            name="Warehouse",
        ),
    ]
