# Generated by Django 6.0.4 on 2026-04-16 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_production_approval(apps, schema_editor):
    ProductionOrder = apps.get_model("production", "ProductionOrder")
    for o in (
        ProductionOrder.objects.filter(approved_at__isnull=True)
        .exclude(status="DRAFT")
        .exclude(status="CANCELLED")
    ):
        o.approved_at = o.started_at or o.completed_at or o.created_at
        o.save(update_fields=["approved_at"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0006_itempackaging_billofmaterials_packaging_and_more"),
        ("production", "0002_alter_productionorder_destination_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_production_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="product",
            field=models.ForeignKey(
                limit_choices_to={"category__in": ["SUB", "FIN"]},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_runs",
                to="bom.item",
            ),
        ),
        migrations.RunPython(backfill_production_approval, noop_reverse),
    ]
