# Generated by Django 6.0.4 on 2026-04-21 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0006_itempackaging_billofmaterials_packaging_and_more"),
        ("production", "0003_purchase_and_production_approval"),
        ("warehouse", "0002_warehousestock_and_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockledger",
            options={"ordering": ["-timestamp", "-pk"]},
        ),
        migrations.AddField(
            model_name="stockledger",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_ledger_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_ledger_entries",
                to="bom.item",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="reference_id",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_ledger_entries",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(
                fields=["item", "-timestamp"], name="production__item_id_d9baa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(
                fields=["warehouse", "-timestamp"],
                name="production__warehou_a3304a_idx",
            ),
        ),
    ]
