# Generated by Django 6.0.4 on 2026-04-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0004_stock_ledger_extend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockledger",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase receipt"),
                    ("PROD_CONSUME", "Production consume"),
                    ("PROD_OUTPUT", "Production output"),
                    ("STOCK_XFER_OUT", "Transfer out"),
                    ("STOCK_XFER_IN", "Transfer in"),
                    ("ITEM_OPENING", "Item opening stock"),
                    ("ADJUSTMENT", "Adjustment"),
                ],
                max_length=20,
            ),
        ),
    ]
