# Generated by Django 6.0.4 on 2026-04-12 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0001_initial"),
        ("warehouse", "0002_warehousestock_and_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="receiving_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipts",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
