# Generated by Django 6.0.4 on 2026-04-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0006_itempackaging_billofmaterials_packaging_and_more"),
        ("procurement", "0002_supplier_blank_email_and_receipt_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="packaging",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipt_lines",
                to="bom.itempackaging",
            ),
        ),
        migrations.AddField(
            model_name="polineitem",
            name="packaging",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_lines",
                to="bom.itempackaging",
            ),
        ),
    ]
