# Generated by Django 6.0.4 on 2026-04-16 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_po_approval(apps, schema_editor):
    PurchaseOrder = apps.get_model("procurement", "PurchaseOrder")
    for po in (
        PurchaseOrder.objects.filter(approved_at__isnull=True)
        .exclude(status="DRAFT")
        .exclude(status="CANCELLED")
    ):
        po.approved_at = po.sent_at or po.created_at
        po.save(update_fields=["approved_at"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0003_goodsreceiptitem_packaging_polineitem_packaging"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_purchase_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_po_approval, noop_reverse),
    ]
