# Generated by Django 6.0.4 on 2026-04-12 06:22

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def backfill_warehouse_stock(apps, schema_editor):
    Item = apps.get_model("bom", "Item")
    Warehouse = apps.get_model("warehouse", "Warehouse")
    WarehouseStock = apps.get_model("warehouse", "WarehouseStock")
    wh = Warehouse.objects.order_by("code").first()
    if wh is None:
        return
    for item in Item.objects.all():
        qty = item.current_stock or Decimal("0")
        if qty > 0:
            WarehouseStock.objects.create(item=item, warehouse=wh, quantity_on_hand=qty)


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0005_remove_warehouse_from_bom_state"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=12
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="bom.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_lines",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "warehouse"),
                        name="warehousestock_unique_item_warehouse",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_warehouse_stock, migrations.RunPython.noop),
    ]
