# Generated by Django 6.0.4 on 2026-04-21 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0006_itempackaging_billofmaterials_packaging_and_more"),
        ("warehouse", "0002_warehousestock_and_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseOutbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "out_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "ship_to",
                    models.CharField(
                        help_text="Client, buyer, or destination label.", max_length=200
                    ),
                ),
                ("is_freebie", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_outbounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_outbounds",
                        to="bom.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbounds",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
