# Generated by Django 6.0.4 on 2026-04-16 06:18

from django.db import migrations, models


def seed_default_settings(apps, schema_editor):
    OrganizationSettings = apps.get_model("prefs", "OrganizationSettings")
    if not OrganizationSettings.objects.exists():
        OrganizationSettings.objects.create(pk=1, currency_code="USD")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        choices=[
                            ("USD", "US dollar (USD)"),
                            ("EUR", "Euro (EUR)"),
                            ("GBP", "Pound sterling (GBP)"),
                            ("INR", "Indian rupee (INR)"),
                            ("NPR", "Nepalese rupee (NPR)"),
                            ("JPY", "Japanese yen (JPY)"),
                            ("AUD", "Australian dollar (AUD)"),
                            ("CAD", "Canadian dollar (CAD)"),
                            ("CHF", "Swiss franc (CHF)"),
                            ("CNY", "Chinese yuan (CNY)"),
                            ("SGD", "Singapore dollar (SGD)"),
                            ("AED", "UAE dirham (AED)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization settings",
                "verbose_name_plural": "Organization settings",
            },
        ),
        migrations.RunPython(seed_default_settings, noop_reverse),
    ]
