# Generated by Django 6.0.4 on 2026-04-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("abbreviation", models.CharField(max_length=10)),
                ("is_base_unit", models.BooleanField(default=False)),
                (
                    "conversion_factor",
                    models.DecimalField(decimal_places=6, default=1.0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UOMCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "UOM Category",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="bom.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("RAW", "Raw"), ("SUB", "Sub"), ("FIN", "Finished")],
                        max_length=3,
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bom.unitofmeasure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_required",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "scrap_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of material lost during production (e.g., 5.00 for 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_components",
                        to="bom.item",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_parents",
                        to="bom.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bom.unitofmeasure",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="bom.uomcategory",
            ),
        ),
    ]
