# Generated by Django 6.0.4 on 2026-04-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("RAW", "Raw"), ("SUB", "Sub"), ("FIN", "Finished")],
                default="RAW",
                max_length=3,
            ),
        ),
    ]
