# Generated by Django 6.0.4 on 2026-04-12 05:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0002_warehouse_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="reorder_level",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("10.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="standard_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
