# Generated by Django 6.0.4 on 2026-04-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0003_item_reorder_level_item_standard_cost"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.UniqueConstraint(
                fields=("product", "component"), name="bom_unique_component_per_product"
            ),
        ),
    ]
