# Generated by Django 6.0.4 on 2026-04-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0005_remove_warehouse_from_bom_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPackaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "units_per_package",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packagings",
                        to="bom.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="packaging",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bom_lines",
                to="bom.itempackaging",
            ),
        ),
        migrations.AddConstraint(
            model_name="itempackaging",
            constraint=models.UniqueConstraint(
                fields=("item", "code"), name="itempackaging_unique_item_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="itempackaging",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("item",),
                name="itempackaging_single_default_per_item",
            ),
        ),
    ]
